### ISSUE TITLE
Compiling fails

### ISSUE THREAD

**Issue by uNiversaI** [notspiff/screensaver.matrixtrails#1]
Apparently it fails because libsoil is missing, I thought that these binary addons were self contained and compiled all required deps?

http://pastebin.com/scpDcHds

installing libsoil-dev fixes this so I guess its missing as a dependency here.

@notspiff

**Comment by notspiff** [comment]
Your observational skills are impecable.
26. sep. 2015 07:42 skrev "uNiversaI" <notifications@github.com>:

**Comment by uNiversaI** [comment]
Great, add to those that the settings do nothing at all.

So I assume by your sarcastic comment that you wont fix the missing libsoil missing issue?

in that case, is there any point to making bug reports to any of these? Because if there isnt we can save each other the aggro to have to deal with any of it.

**Comment by notspiff** [comment]
what is missing= soil is a dependency, you need to provide it. like for
every other piece of software. end of story.
i'm not agressive. i just don't understand why you are telling me things i
know very well.

**Comment by uNiversaI** [comment]
Well, since theres no documentation and all other addons seem to compile all required libs (like audio encoders compile lame) I thought soil fell into this category.

but since you rather be obtuse, I wont bother make any reports.

**Comment by notspiff** [comment]
i don't know what made you think those are selfcontained.

lame links libmp3lame
vorbis links libvorbisenc

on linux we use these from system libraries cause that's what you do on
linux.
on other platforms, we build the dependencies using the unified depends
system. that's those depends/<platform>/<txt files> you see. but since this
thing only depends on libsoil on linux, ie. only as a system depends,
untill somebody ports to osx (and you know that won't be me!), there is no
need for any depends.
windows uses the directx code for image loading.

please do open the issues. i just get a little grumpy when it's stupid
things (from my pov!) ignore my social limitations..

**Comment by notspiff** [comment]
Put a note in README.md

**Comment by uNiversaI** [comment]
Well lame and vorbis seem to build those even on Linux, I uninstalled both dev packages and they still compile anyway....

**Comment by notspiff** [comment]
well yes, linux isnt excluded once the depends is there. this is for
testing on jenkins foremost, the debs etc use system libs.
